<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>yudao-module-flink</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>yudao-flink-common-deploy</module>
        <module>yudao-flink-common</module>
        <module>yudao-flink-job-listener</module>
        <module>yudao-flink-monitor</module>
    </modules>
    <description>
        Flink 模块
    </description>

    <properties>
        <flink.scope>compile</flink.scope>
    </properties>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <flink.scope>compile</flink.scope>
                <shade.plugin.skip>true</shade.plugin.skip>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <flink.scope>provided</flink.scope>
                <shade.plugin.skip>false</shade.plugin.skip>
            </properties>
        </profile>
    </profiles>


</project>