### 请求 /system/mail-template/send-mail 接口 => 成功
< {%
    request.variables.set("baseUrl", "http://localhost:8089")
    request.variables.set("adminTenantId", "1")
    request.variables.set("token", "test1")
%}
POST {{baseUrl}}/system/mail-template/send-mail
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{
  "templateCode": "test_01",
  "mail": "7685413@qq.com",
  "templateParams": {
    "key01": "value01",
    "key02": "value02"
  }
}



