<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <groupId>cn.iocoder.yudao</groupId>
    <artifactId>yudao-module-data-studio</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>yudao-module-data-studio</name>
    <description>
        yudao-module-data-studio
        数据中台模块
    </description>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>yudao-module-data-studio-biz</module>
        <module>yudao-module-data-studio-api</module>
    </modules>




</project>
